import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Layout } from '@/components/Layout';
import Navbar from '@/components/navbar';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <nav style={{
        backgroundImage: "url(" + "https://github.com/lebe24/varion/blob/main/agent%201%201.png?raw=true" + ")",

        border: '1px solid blue' ,
        width:'200rem',
        height:'300rem'
    }}>
      hello
    </nav>
      </Layout>
    </>
  )
}
